### ISSUE TITLE
simple cipher

### ISSUE THREAD

**Issue by calancha** [Dalbukerk/BackdoorBeginnerCTF#1]
How did you conclude that 'SDSLabs' is the key?
Just a lucky guess? Or did you follow some approach instead?
Thank you

**Comment by H3rm1tR3b0rn** [comment]
The challenge says " with help of SDSLabs", so I thought that was the key.

Em sáb, 24 de nov de 2018 21:13, Tino Calancha <notifications@github.com>
escreveu:

**Comment by calancha** [comment]
> The challenge says " with help of SDSLabs", so I thought that was the key. 
A clear example of 'lateral thinking'; a must-have skill for this kind of challenges.
Thank you
